CALL OBSERVABILITY_SETUP.setup_procedures_v1.FEDERATED_CRON_SETUP('IE93671', 'alonso.sevilla@wahlclipper.com');
CREATE OR REPLACE PROCEDURE OBSERVABILITY_SETUP.setup_procedures_v1.FEDERATED_CRON_SETUP(ACCOUNT VARCHAR, INFRA_EMAIL VARCHAR)
  RETURNS STRING
  LANGUAGE javascript
  EXECUTE AS CALLER
  AS 
  $$

  var version_schema = "setup_procedures_v1"; 

  var account = ACCOUNT;
  var infra_email = INFRA_EMAIL;

  var role_creation = `
    BEGIN 
    USE ROLE ACCOUNTADMIN;
    USE ROLE ACCOUNTADMIN;
    GRANT ALL ON DATABASE IE93671_KH_SNOWFLAKE_COSTING TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON DATABASE IE93671_OBSERVABILITY TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON ALL SCHEMAS IN DATABASE IE93671_KH_SNOWFLAKE_COSTING TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON ALL SCHEMAS IN DATABASE IE93671_OBSERVABILITY TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON ALL SCHEMAS IN DATABASE OBSERVABILITY_SETUP TO ROLE OBSERVABILITY_ADMIN;
    GRANT USAGE ON ALL PROCEDURES IN DATABASE OBSERVABILITY_SETUP TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON ALL TABLES IN SCHEMA IE93671_KH_SNOWFLAKE_COSTING.SNOWFLAKE_COST_STD TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON ALL TABLES IN SCHEMA IE93671_OBSERVABILITY.OBSERVABILITY_CORE TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON FUTURE TABLES IN SCHEMA IE93671_KH_SNOWFLAKE_COSTING.SNOWFLAKE_COST_STD TO ROLE OBSERVABILITY_ADMIN;
    GRANT ALL ON FUTURE TABLES IN SCHEMA IE93671_OBSERVABILITY.OBSERVABILITY_CORE TO ROLE OBSERVABILITY_ADMIN;
    USE ROLE OBSERVABILITY_ADMIN; 
    USE WAREHOUSE OBSERVABILITY_WH;
    END;`;

  var statement0 = snowflake.createStatement({sqlText: role_creation});
  var role = statement0.execute();
  role.next();
  role_output = role.getColumnValue(1)

  $$;