BEGIN
  -- Create the necessary databases and schemas
  CREATE DATABASE IF NOT EXISTS OBSERVABILITY_SETUP;
  CREATE SCHEMA IF NOT EXISTS OBSERVABILITY_SETUP.setup_procedures_v1;
  CREATE SCHEMA IF NOT EXISTS OBSERVABILITY_SETUP.VERSION_CONFIG;
  
  -- Create the version by account table
  CREATE TABLE IF NOT EXISTS OBSERVABILITY_SETUP.VERSION_CONFIG.VERSION_BY_ACCOUNT (
    ACCOUNT_LOCATOR VARCHAR,
    OBSERVABILITY_VERSION VARCHAR
  );
  
  -- Create the maintenance database and logging schema
  CREATE DATABASE IF NOT EXISTS OBSERVABILITY_MAINTENANCE;
  CREATE SCHEMA IF NOT EXISTS OBSERVABILITY_MAINTENANCE.LOGGING_SCHEMA;
  
  -- Create the logging table
  CREATE TRANSIENT TABLE IF NOT EXISTS OBSERVABILITY_MAINTENANCE.LOGGING_SCHEMA.LOGGING_TABLE (
    PROCEDURE_NAME VARCHAR,
    STATUS VARCHAR,
    DESC VARCHAR,
    ACCOUNT VARCHAR
  );
